<?php

namespace Cps\informaticaBundle\Repository;

/**
 * asignarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class asignarRepository extends \Doctrine\ORM\EntityRepository
{
}
