<?php

namespace Cps\informaticaBundle\Repository;

/**
 * personalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personalRepository extends \Doctrine\ORM\EntityRepository
{
}
