<?php

namespace Cps\informaticaBundle\Repository;

/**
 * remitenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class remitenteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAjaxValue($term){
        return $this->getEntityManager()
        ->createQuery(
            'SELECT p FROM CpsinformaticaBundle:remitente p
                      WHERE p.nombre LIKE :value')
            ->setParameter('value','%'.$term.'%')
            ->getResult();
    }
}
