<?php

namespace Cps\informaticaBundle\Repository;

/**
 * servicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class servicioRepository extends \Doctrine\ORM\EntityRepository
{
}
