<?php

namespace Cps\informaticaBundle\Repository;

/**
 * solicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class solicitudRepository extends \Doctrine\ORM\EntityRepository
{
  public function spendiente($searchQuery){
      $emp=$this->getEntityManager();
      $query = $emp->createQuery("SELECT s.id, s.ruta, s.fecha, s.cite, s.referencia, r.nombre, s.estado
                                   FROM CpsinformaticaBundle:solicitud s
                                   JOIN s.remitente r
                                   where s.ruta LIKE '%$searchQuery%' and s.estado = 1 ORDER BY s.ruta ASC");
      $result = $query->getResult();
      return $result;
  }
  public function sproceso($searchQuery){
      $emp=$this->getEntityManager();
      $query = $emp->createQuery("SELECT s.id, s.ruta, s.fecha, s.cite, s.referencia, r.nombre, s.estado
                                   FROM CpsinformaticaBundle:solicitud s
                                   JOIN s.remitente r
                                   where s.ruta LIKE '%$searchQuery%' and s.estado = 2 ORDER BY s.ruta ASC");
      $result = $query->getResult();
      return $result;
  }
  public function srealizado($searchQuery){
      $emp=$this->getEntityManager();
      $query = $emp->createQuery("SELECT s.id, s.ruta, s.fecha, s.cite, s.referencia, r.nombre, s.estado
                                   FROM CpsinformaticaBundle:solicitud s
                                   JOIN s.remitente r
                                   where s.ruta LIKE '%$searchQuery%' and  s.estado = 3 ORDER BY s.ruta ASC");
      $result = $query->getResult();
      return $result;
  }
  public function busPersonal($solicitud_id){
      $emp=$this->getEntityManager();
      $query = $emp->createQuery("SELECT p.nom, p.app, p.apm, p.pref
                                   FROM CpsinformaticaBundle:asignar a
                                   JOIN a.personal p
                                   where a.solicitud = '$solicitud_id'");
      $result = $query->getResult();
      return $result;
  }
  public function rnombre($searchQuery){
      $emp=$this->getEntityManager();
      $query = $emp->createQuery("SELECT s.id, s.ruta, s.fecha, s.cite, s.referencia, r.nombre, s.estado
                                   FROM CpsinformaticaBundle:solicitud s
                                   JOIN s.remitente r
                                   where r.nombre LIKE '%$searchQuery%' ORDER BY s.ruta ASC");
      $result = $query->getResult();
      return $result;
  }
}